name: Deployment to S3 Bucket
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Set Current Datetimes
        id: set_datetime
        run: echo "::set-output name=DATETIME::$(date -u +"%Y-%m-%dT%H:%M:%SZ")"

      - name: Echoing var
        run: echo "flutter_web_${{ steps.set_datetime.outputs.DATETIME }}"

      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Flutter
        uses: subosito/flutter-action@v2

      - name: Install Dependencies
        run: flutter pub get

      - name: Build Flutter Web
        run: flutter build web

      - name: Zip web folder
        run: Compress-Archive -Path 'build/web/*' -DestinationPath "abcd.zip"

      - name: Upload to AWS S3
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Upload abcd.zip to S3 Buckets
        run: aws s3 cp abcd.zip s3://amplify-development/abcd.zip

      - name: Deploy to AWS Amplify
        run: aws amplify start-deployment --app-id d1zb6sew1l51g3 --branch-name prod --source-url s3://amplify-development/abcd.zip