name: Amplify Deploy

on:
  push:
    branches:
      - master
      - test

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 14

      - name: Install Amplify CLI
        run: npm install -g @aws-amplify/cli

      - name: Configure AWS credentials
        run: |
          echo "AWS_ACCESS_KEY_ID=AKIAQ3E6XAIHSWGF345T" >> $GITHUB_ENV
          echo "AWS_SECRET_ACCESS_KEY=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" >> $GITHUB_ENV
          amplify configure set region ap-south-1

      - name: Install dependencies
        run: npm install

      - name: Deploy to Amplify (Master)
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        run: amplify publish

      - name: Deploy to Amplify (Test)
        if: github.event_name == 'push' && github.ref == 'refs/heads/test'
        run: amplify publish --env test
