name: Deploy to AWS Amplify

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v2

      - name: Install dependencies
        run: flutter pub get

      - name: Build release APK
        run: flutter build web --release -t lib/main_dev.dart

      - name: Create artifact directory
        run: mkdir artifact

      - name: Copy web folder to artifact
        run: cp -r build/web/. artifact/

      - name: List contents of artifact directory
        run: ls artifact/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Install AWS CLI
        run: |
          sudo apt-get install -y awscli

      - name: Configure AWS CLI
        run: |
          aws configure set aws_access_key_id AKIAQ3E6XAIHSWGF345T
          aws configure set aws_secret_access_key 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
          aws configure set region ap-south-1

      - name: Deploy to AWS Amplify
        run: |
          aws amplify start-deployment --app-id d3iqc5dpxs0nxf --branch-name master --source-dir artifact/
