name: Deploy to AWS Amplify

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v2

      - name: Install dependencies
        run: flutter pub get

      - name: Build release APK
        run: flutter build web --release -t lib/main_dev.dart

      - name: Create artifact directory
        run: mkdir artifact

      - name: Copy web folder to artifact
        run: cp -r build/web/. artifact/

      - name: List contents of artifact directory
        run: ls artifact/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Install Amplify CLI
        run: |
          sudo apt-get install -y nodejs
          sudo npm install -g @aws-amplify/cli
          

      - name: Configure Amplify CLI
        run: |
          amplify configure --appId d3iqc5dpxs0nxf
          amplify configure --branch master

      - name: Deploy to AWS Amplify
        uses: aws-amplify/amplify-action@v1
        with:
          amplifyAppId: d3iqc5dpxs0nxf
          amplifyBranch: master
          dir: artifact/web
        env:
          AWS_ACCESS_KEY_ID: AKIAQ3E6XAIHSWGF345T
          AWS_SECRET_ACCESS_KEY: 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
          AWS_REGION: ap-south-1
