name: Deploy to AWS Amplify

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install Dependencies
        run: |
          npm install
          # Additional setup steps if needed

      - name: Build Flutter Web Release
        run: flutter build web --release

  create-release:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.sha }}
          release_name: Release ${{ github.sha }}
          draft: false
          prerelease: false

  upload-artifact:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Archive Release Artifact
        uses: actions/upload-artifact@v2
        with:
          name: release-artifact
          path: build/web

  download-artifact:
    runs-on: ubuntu-latest
    needs: upload-artifact

    steps:
      - name: Download Release Artifact
        uses: actions/download-artifact@v2
        with:
          name: release-artifact
          path: downloaded-artifact

  configure-aws:
    runs-on: ubuntu-latest
    needs: download-artifact

    steps:
      - name: Configure AWS CLI
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws configure set region ${{ secrets.AWS_REGION }}

  deploy-to-amplify:
    runs-on: ubuntu-latest
    needs: configure-aws

    steps:
      - name: Configure Amplify
        run: npx amplify configure

      - name: Deploy to Amplify
        run: npx amplify publish --appId App_name --envName amplify123

on:
  workflow_run:
    workflows: ["Deploy to AWS Amplify"]
    types:
      - completed
