name: Deploy to AWS Amplify

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v2

      - name: Install dependencies
        run: flutter pub get

      - name: Build release APK
        run: flutter build web --release -t lib/main.dart

      - name: Create artifact directory
        run: mkdir artifact

      - name: Copy web folder to artifact
        run: cp -r build/web/. artifact/

      - name: List contents of artifact directory
        run: ls -R artifact/

      - name: List contents of web folder
        run: ls -R build/web/

      - name: Zip web folder
        run: Compress-Archive -Path 'build/web/*' -DestinationPath 'artifact/hello.zip'

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: AKIA5QVGJAZV243EIIQ3
          aws-secret-access-key: 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
          aws-region: ap-south-1

      - name: List Zip Files in S3 Bucket
        run: aws s3 ls s3://amplify-web-sunfox/ --recursive | grep '.zip' || true

      - name: Delete All Files in S3 Bucket
        run: aws s3 rm s3://amplify-web-sunfox/ --recursive || true

      - name: Upload hello.zip to S3 Bucket
        run: aws s3 cp artifact/hello.zip s3://amplify-web-sunfox/hello.zip

      - name: List Zip Files in S3 Buckets
        run: aws s3 ls s3://amplify-web-sunfox/ --recursive | grep '.zip' || true
