name: Flutter Web Deploy

on:
  push:
    branches:
      - master  # Change this to your main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.13.9'  # Adjust to the Flutter version you're using

      - name: Update Flutter and Dart SDK
        run: |
            flutter upgrade
            flutter pub upgrade
#      - name: Add cupertino_icons to dependencies
#        run: flutter pub add cupertino_icons
#             flutter pub add get
#             flutter pub add fluttertoast

      - name: Install Dependencies
        run: flutter pub get


      - name: Build Flutter Web --releases
        run: flutter build web  --release -t lib/main_prod.dart

  deploy:
    runs-on: ubuntu-latest

    needs: build

    steps:
      - name: Archive Web Build
        uses: actions/upload-artifact@v2
        with:
          name: web
          path: build/web

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: AKIAQ3E6XAIHXMY46QVX
          aws-secret-access-key: 01I31MkEYHTF/EAMC4rks6nic5oA96Lc6vFmObgw
          aws-region: ap-south-1  # Replace with your AWS region

      - name: Deploy to AWS Amplify
        run: |
          amplify init --amplify {
            "frontend": "javascript",
            "framework": "flutter"
          }
          amplify publish

