name: Deployment to S3 Bucket
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Set Current Date
        id: set_date
        run: echo "::set-output name=DATE::$(Get-Date -Format 'yyyyMMdd')"

      - name: Echoing var
        run: echo "flutter_web_${{ steps.set_date.outputs.DATE }}"

      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Flutter
        uses: subosito/flutter-action@v2

      - name: Install Dependencies
        run: flutter pub get

      - name: Build Flutter Web
        run: flutter build web --release -t lib/main_prod.dart

      - name: Zip web folder
        run: Compress-Archive -Path 'build/web/*' -DestinationPath "flutter_web_${{ steps.set_date.outputs.DATE }}.zip"

      - name: Upload to AWS S3
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Upload zip to S3 Bucket
        run: aws s3 cp "flutter_web_${{ steps.set_date.outputs.DATE }}.zip" s3://amplify-${{ github.event_name }}/"flutter_web_${{ steps.set_date.outputs.DATE }}.zip"

      - name: Deploy to AWS Amplify
        run: aws amplify start-deployment --app-id d1zb6sew1l51g3 --branch-name prod --source-url s3://amplify-development/abcd.zip