on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: windows-latest

    env:
      BRANCH_NAME: master
      APP_ID: d19yevjv3ahi39  # Replace with your actual Amplify App ID

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node.js and Install Dependencies
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install Amplify CLI
        run: npm i aws-amplify

      - name: Configure AWS credentials
        run: |
          aws configure set aws_access_key_id AKIAQ3E6XAIHSWGF345T
          aws configure set aws_secret_access_key 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
          aws configure set region ap-south-1

      - name: Display Branch and App ID
        run: |
          echo "Branch Name: master"
          echo "Amplify App ID: d19yevjv3ahi39"

      - name: Deploy to Amplify
        run: |
            # Navigate to the build/web directory
            cd build/web

      - name: Amplify Push
        run: amplify push --yes

      - name: Amplify Publish
        run: amplify publish --yes
